tolerance: 15.0
container: regular
pouring_position: edge
controller:
  type: pd
  morphology:
  p_gain: 0.0025
  d_gain: 0.01
  max_acc_scaling: 1
  max_vel_scaling: 0.5
  rot_axis: [1, 0, 0]
  shaking: True
  shake_params:
    axis: [0, 1, 0]
    amplitude: 0.005
    frequency: 2
