tolerance: 5.0
container: regular
pouring_position: corner
controller:
  type: pd
  morphology:
  p_gain: 0.0025
  d_gain: 0.01
  max_acc_scaling: 1
  max_vel_scaling: 1
  rot_axis: [0, 0, -1]
  shaking: False
