name: onion
tolerance: 20.0
container: regular
pouring_position: edge
controller:
  type: pd
  error_threshold: 8.0
  p_gain: 0.0025
  d_gain: 0.02
  acc_scaling: 2
  vel_scaling: 1
  rot_axis: [1, 0, 0]
  shaking: True
  trans_shake_params:
    axis: [0, 1, 0]
    amplitude: 0.01
    frequency: 4
    pattern: [0, 1, 0, 0, 0, 0]

  # Done without engineered lid
  # Tried for 100g, 300g, 325g - works very well
  # Tried for 30 -> reached 27g. So good!!
