peanuts: 916
cucumber: 884
vinegar: 1562
salt: 500
blackpepper: 500
lentils: 250
cumin_seeds:  1000
mustard_seeds: 1000
sunflower_oil: 1000
turmeric: 1000
onion: 1000
poha_thick: 1000
green_chillies: 1000
water: 1000