peanuts: 916
cucumber: 884
vinegar: 1562
salt: 500
blackpepper: 500
lentils: 250
sunflower_oil: 500
mustard_seeds: 500
cumin_seeds: 500
water: 500
onion: 500
green_chillies: 500
poha_thick: 500
noodle: 500
turmeric: 500
position-12: 500
position-13: 500
position-14: 500
position-15: 500