- id: 1
  name: Paneer_fried_rice
  ingredients:
  - name: sunflower_oil
    quantity: 10
  - name: cumin_seeds
    quantity: 5
  - name: ginger_garlic_paste
    quantity: 20  
  - name: salt
    quantity: 8
  - name: onion
    quantity: 150
  - name: _wait
    quantity: 180
  - name: paneer
    quantity: 220
  - name: _wait
    quantity: 120
  - name: kitchen_king
    quantity: 5
  - name: turmeric
    quantity: 2   
  - name: water
    quantity: 550   
  - name: rice
    quantity: 200 
- id: 2
  name: Pasta
  ingredients:
  - name: sunflower_oil
    quantity: 15
  - name: onion
    quantity: 100    
  - name: _wait
    quantity: 120
  - name: garlic_powder
    quantity: 3
  - name: salt
    quantity: 5
  - name: black_pepper
    quantity: 1  
  - name: oregano
    quantity: 1
  - name: marinara
    quantity: 300
  - name: _wait
    quantity: 90
  - name: bell_pepper
    quantity: 100
  - name: cheese
    quantity: 100 
  - name: water
    quantity: 500
  - name: _wait
    quantity: 40
  - name: pasta
    quantity: 225 
- id: 3
  name: sunflower_oil
  ingredients:
  - name: sunflower_oil
    quantity: 15  
- id: 4
  name: onion
  ingredients:
  - name: onion
    quantity: 10  
- id: 5
  name: garlic_powder
  ingredients:
  - name: garlic_powder
    quantity: 3  
- id: 6
  name: marinara
  ingredients:
  - name: marinara
    quantity: 300  
- id: 7
  name: salt
  ingredients:
  - name: salt
    quantity: 5  
- id: 8
  name: black_pepper
  ingredients:
  - name: black_pepper
    quantity: 1  
- id: 9
  name: oregano
  ingredients:
  - name: oregano
    quantity: 3  
- id: 10
  name: water
  ingredients:
  - name: water
    quantity: 500  
- id: 11
  name: pasta
  ingredients:
  - name: pasta
    quantity: 225  
- id: 12
  name: lentils
  ingredients:
  - name: lentils
    quantity: 10  
- id: 13
  name: bell_pepper
  ingredients:
  - name: bell_pepper
    quantity: 100  

