- !recipe
  id: 1
  name: Paneer_fried_rice
  ingredients:
  - !ingredient
    name: sunflower_oil
    quantity: 10
  - !ingredient
    name: cumin_seeds
    quantity: 5
  - !ingredient
    name: ginger_garlic_paste
    quantity: 20
  - !ingredient
    name: salt
    quantity: 8
  - !ingredient
    name: onion
    quantity: 150
  - !ingredient
    name: _wait
    quantity: 180
  - !ingredient
    name: paneer
    quantity: 220
  - !ingredient
    name: _wait
    quantity: 120
  - !ingredient
    name: kitchen_king
    quantity: 5
  - !ingredient
    name: turmeric
    quantity: 2
  - !ingredient
    name: water
    quantity: 550
  - !ingredient
    name: rice
    quantity: 200
- !recipe
  id: 2
  name: Pasta
  ingredients:
  - !ingredient
    name: sunflower_oil
    quantity: 15
  - !ingredient
    name: onion
    quantity: 100
  - !ingredient
    name: _wait
    quantity: 120
  - !ingredient
    name: garlic_powder
    quantity: 3
  - !ingredient
    name: salt
    quantity: 5
  - !ingredient
    name: black_pepper
    quantity: 1
  - !ingredient
    name: oregano
    quantity: 1
  - !ingredient
    name: marinara
    quantity: 300
  - !ingredient
    name: _wait
    quantity: 90
  - !ingredient
    name: bell_pepper
    quantity: 100
  - !ingredient
    name: cheese
    quantity: 100
  - !ingredient
    name: water
    quantity: 500
  - !ingredient
    name: _wait
    quantity: 40
  - !ingredient
    name: pasta
    quantity: 225
- !recipe
  id: 3
  name: sunflower_oil
  ingredients:
  - !ingredient
    name: sunflower_oil
    quantity: 15
- !recipe
  id: 4
  name: onion
  ingredients:
  - !ingredient
    name: onion
    quantity: 10
- !recipe
  id: 5
  name: garlic_powder
  ingredients:
  - !ingredient
    name: garlic_powder
    quantity: 3
- !recipe
  id: 6
  name: marinara
  ingredients:
  - !ingredient
    name: marinara
    quantity: 300
- !recipe
  id: 7
  name: salt
  ingredients:
  - !ingredient
    name: salt
    quantity: 5
- !recipe
  id: 8
  name: black_pepper
  ingredients:
  - !ingredient
    name: black_pepper
    quantity: 1
- !recipe
  id: 9
  name: oregano
  ingredients:
  - !ingredient
    name: oregano
    quantity: 3
- !recipe
  id: 10
  name: water
  ingredients:
  - !ingredient
    name: water
    quantity: 500
- !recipe
  id: 11
  name: pasta
  ingredients:
  - !ingredient
    name: pasta
    quantity: 225
- !recipe
  id: 12
  name: lentils
  ingredients:
  - !ingredient
    name: lentils
    quantity: 10
- !recipe
  id: 13
  name: bell_pepper
  ingredients:
  - !ingredient
    name: bell_pepper
    quantity: 100
- !recipe
  id: 21
  name: Pasta
  ingredients:
  - !ingredient
    name: sunflower_oil
    quantity: 15
  - !ingredient
    name: onion
    quantity: 100
  - !ingredient
    name: _wait
    quantity: 120
  - !ingredient
    name: garlic_powder
    quantity: 3
  - !ingredient
    name: salt
    quantity: 5
  - !ingredient
    name: black_pepper
    quantity: 1
  - !ingredient
    name: oregano
    quantity: 1
  - !ingredient
    name: marinara
    quantity: 300
  - !ingredient
    name: _wait
    quantity: 90
  - !ingredient
    name: bell_pepper
    quantity: 100
  - !ingredient
    name: cheese
    quantity: 100
  - !ingredient
    name: water
    quantity: 500
  - !ingredient
    name: _wait
    quantity: 40
  - !ingredient
    name: pasta
    quantity: 225
- !recipe
  id: 22
  name: Pasta
  ingredients:
  - !ingredient
    name: sunflower_oil
    quantity: 15
  - !ingredient
    name: onion
    quantity: 100
  - !ingredient
    name: _wait
    quantity: 120
  - !ingredient
    name: garlic_powder
    quantity: 3
  - !ingredient
    name: salt
    quantity: 5
  - !ingredient
    name: black_pepper
    quantity: 1
  - !ingredient
    name: oregano
    quantity: 1
  - !ingredient
    name: marinara
    quantity: 300
  - !ingredient
    name: _wait
    quantity: 90
  - !ingredient
    name: cheese
    quantity: 100
  - !ingredient
    name: water
    quantity: 500
  - !ingredient
    name: _wait
    quantity: 40
  - !ingredient
    name: pasta
    quantity: 225
- !recipe
  id: 23
  name: Pasta
  ingredients:
  - !ingredient
    name: sunflower_oil
    quantity: 15
  - !ingredient
    name: onion
    quantity: 100
  - !ingredient
    name: _wait
    quantity: 120
  - !ingredient
    name: garlic_powder
    quantity: 3
  - !ingredient
    name: salt
    quantity: 5
  - !ingredient
    name: black_pepper
    quantity: 1
  - !ingredient
    name: marinara
    quantity: 300
  - !ingredient
    name: _wait
    quantity: 90
  - !ingredient
    name: bell_pepper
    quantity: 100
  - !ingredient
    name: cheese
    quantity: 100
  - !ingredient
    name: water
    quantity: 500
  - !ingredient
    name: _wait
    quantity: 40
  - !ingredient
    name: pasta
    quantity: 225
- !recipe
  id: 24
  name: Pasta
  ingredients:
  - !ingredient
    name: sunflower_oil
    quantity: 15
  - !ingredient
    name: onion
    quantity: 100
  - !ingredient
    name: _wait
    quantity: 120
  - !ingredient
    name: garlic_powder
    quantity: 3
  - !ingredient
    name: salt
    quantity: 5
  - !ingredient
    name: black_pepper
    quantity: 1
  - !ingredient
    name: marinara
    quantity: 300
  - !ingredient
    name: _wait
    quantity: 90
  - !ingredient
    name: cheese
    quantity: 100
  - !ingredient
    name: water
    quantity: 500
  - !ingredient
    name: _wait
    quantity: 40
  - !ingredient
    name: pasta
    quantity: 225