- id: 1
  name: Poha
  ingredients:
  - name: "greenolives"
    quantity: 40
  - name: "salt"
    quantity: 23
- id: 2
  name: Pasta
  ingredients:
  - name: "blackpepper"
    quantity: 10
  - name: _wait
    quantity: 2
  - name: water
    quantity: 5
  
